SELECT * FROM EMANET

SELECT * FROM KITAPLAR
SELECT * FROM UYELER
SELECT * FROM ADRESLER
SELECT * FROM KUTUPHANE

INSERT INTO KITAPLAR VALUES ('1224','TUTUNAMAYANLAR', '10.01.2010',200);
INSERT INTO ADRESLER VALUES ('MEVLANA', '15 TEMMUZ','TBMYO','KAYSERI',253,'TURKÝYE');
INSERT INTO UYELER VALUES('SEMÝH', 'GÜNEY', 'E',2424, 'SEMIHGUNEY@GMAIL.COM',1);
INSERT INTO KUTUPHANE VALUES('KAYSERÝ ÜNÝ', 'MERKEZ',1)
INSERT INTO EMANET VALUES('1224',1,1,'2020-02-10','2022-10-01')