SELECT * FROM KITAPLAR
SELECT * FROM ADRESLER
SELECT * FROM UYELER
SELECT * FROM KUTUPHANE
SELECT * FROM EMANET
SELECT * FROM KATEGORILER
SELECT * FROM YAZARLAR
SELECT * FROM KITAP_KATEGORI
SELECT * FROM KITAP_KUTUPHANE
SELECT * FROM KITAP_YAZAR

INSERT INTO KITAPLAR VALUES ('1224','TUTUNAMAYANLAR', '10.03.1972',671);
INSERT INTO KITAPLAR VALUES ('1245','TEHLİKELİ OYUNLAR','26.05.1973',479);
INSERT INTO ADRESLER VALUES ('MEVLANA', '15 TEMMUZ','TBMYO','KAYSERİ',38000,'TÜRKİYE');
INSERT INTO ADRESLER VALUES ('KORKMAZLAR','ODUNCU','F BLOK','BURSA',16000,'TÜRKİYE');
INSERT INTO UYELER VALUES ('SEMİH', 'GÜNEY', 'E','05445556677', 'SEMIHGUNEY@GMAIL.COM',7);
INSERT INTO UYELER VALUES ('MEHMET','KORKMAZ','E','05553334455','MEHMETKORKMAZ@GMAIL.COM',8);
INSERT INTO KUTUPHANE VALUES ('KAYSERİ ANA', 'MERKEZ',7);
INSERT INTO KUTUPHANE VALUES ('ULUDAĞ ANA','ULUDAĞ ÜNİVERSİTESİ',8);
INSERT INTO EMANET VALUES ('1224',13,2,'2020-02-10','2022-10-01');
INSERT INTO EMANET VALUES ('1245',12,1,'2021-04-07','2023-10-12');
INSERT INTO KATEGORILER VALUES ('ROMAN');
INSERT INTO KATEGORILER VALUES ('BİLİM KURGU'); 
INSERT INTO YAZARLAR VALUES ('OĞUZ','ATAY');
INSERT INTO YAZARLAR VALUES ('GEORGE','ORWELL');
INSERT INTO KITAP_KATEGORI VALUES ('1224',1);
INSERT INTO KITAP_KATEGORI VALUES ('1245',1);
INSERT INTO KITAP_KUTUPHANE VALUES (1,'1224',3);
INSERT INTO KITAP_KUTUPHANE VALUES (2,'1245',7);
INSERT INTO KITAP_YAZAR VALUES ('1224',3);
INSERT INTO KITAP_YAZAR VALUES ('1245',3);
